#!/usr/bin/env python

info = {
    'mkdir': {
      'prompt': 'Does mkdir a) create a new directory, or b) make a delivery?',
      'answer': 'a',
      'wrong_answer': 'Oops. That\'s wrong. mkdir creates a new directory'
      },
    'echo' : {
      'prompt': 'Does echo a) increase your computer volume, or b) print some arguments?',
      'answer': 'b',
      'wrong_answer': 'Oops. That\'s wrong. echo prints some arguments'
      },
    'xargs': {
      'prompt': 'Does xargs mean a) delete the arguments, or b) execute the arguments?',
      'answer': 'b',
      'wrong_answer' : 'Oops. That\'s wrong. xargs means execute the arguments'
      },
    'cat' : {
      'prompt': 'Does cat a) call a category, or b) prints the whole file?',
      'answer': 'b',
      'wrong_answer': 'Oops. That\'s wrong. cat prints the whole file'
      },
    'pwd': {
      'prompt': 'Does pwd mean a) password, or b) print working directory?',
      'answer': 'b',
      'wrong_answer': 'Oops. That\'s wrong. pwd means print working directory'
      },
    'ls': {
      'prompt': 'Does ls mean a) lost system, or b) list directory?',
      'answer': 'b',
      'wrong_answer': 'Oops. That\'s wrong. ls means list directory'
      },
    'cd' : {
      'prompt': 'Does cd mean a) change directory, or b) compact disc?',
      'answer': 'a',
      'wrong_answer': 'Oops. That\'s wrong. cd means change directory'
      },
    'hostname' : {
      'prompt': 'Does hostname mean a) the computer\'s network name, or b) the encrypted wifi name?',
      'answer': 'a',
      'wrong_answer': 'Oops. That\'s wrong. hostname is the computer\'s network name'
      },
    'rmdir' : {
      'prompt': 'Does rmdir mean a) repair directory, or b) remove directory?',
      'answer': 'b',
      'wrong_answer': 'Oops. That\'s wrong. rmdir means remove directory'
      },
    'man' : {
      'prompt': 'Does man mean a) manipulate the variable, or b) read a manual page?',
      'answer':  'b',
      'wrong_answer': 'Oops. That\'s wrong. man means read a manual page'
      },
    }

def shuffle(a):
  return random.sample(a, len(a))

def ask(command):
    data = info[command]
    question = raw_input(info[command]['prompt'] + ' ')

    if question == info[command]['answer']:
            print "Correct! Good job!"
            return True
    else:
            print info[command]['wrong_answer']
            return False

#------------------------------------------------------------

print "Welcome to Programming Commands for Newbies!"
print "Learning these commands will make programming easy and fun!"
print "Before we begin,"

answer = raw_input("what is your name? ")

if len(answer) > 0:
	print "Nice to meet you, " + answer + "!" + " Let's play!"

total = 0
correct = 0
for item in info.keys():
	total += 1
    if ask(item):
    	correct += 1

print "Thank you for playing " + answer + "!"
print "You have " + str(correct) +  "/" + str(total)





